name: hello-server-artifact

on: [push]

env:
  FILE_NAME: hello-server

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Build ${{ env.FILE_NAME }}
        run: go build ${{ env.FILE_NAME }}.go
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: linux
          path: ./${{ env.FILE_NAME }}
  test-linux:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: linux
      - name: Test ${{ env.FILE_NAME }}
        run: source ./hello-server-go-test.sh
        
